name: Docker publish

on:
  release:
    types: [ published ]
  push:

env:
  REGISTRY: ghcr.io
  # Note: github.repository corresponds to <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  DOCKERFILE_NAME: Dockerfile
  DOCKER_DIR_FOO: foo
  IMAGE_TAG_FOO: foo
  DOCKER_DIR_BAR: bar
  IMAGE_TAG_BAR: bar
  IMAGE_CACHE_DIR_FOO: /tmp/.buildx-cache-foo/
  IMAGE_TAR_FILE_FOO: image-foo.tar
  IMAGE_CACHE_DIR_BAR: /tmp/.buildx-cache-bar/

jobs:
  build-foo:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Buildx is necessary for exporting images
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Initialize cache for storing docker image
        uses: actions/cache@v3
        with:
          path: ${{ env.IMAGE_CACHE_DIR_FOO }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}-foo
          restore-keys: |
            ${{ runner.os }}-buildx-foo-

      - name: Ensure cache dir exists
        run: if [ ! -d "${{ env.IMAGE_CACHE_DIR_FOO }}" ]; then mkdir ${{ env.IMAGE_CACHE_DIR_FOO }}; fi

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build image
      - name: Build and cache image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: docker/${{ env.DOCKER_DIR_FOO }}
          file: docker/${{ env.DOCKER_DIR_FOO }}/${{ env.DOCKERFILE_NAME }}
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_FOO }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=${{ env.IMAGE_CACHE_DIR_FOO }}/${{ env.IMAGE_TAR_FILE_FOO }}

  cache-bar:
    runs-on: ubuntu-latest
    needs: build-foo

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore foo docker image cache
        uses: actions/cache@v3
        with:
          path: ${{ env.IMAGE_CACHE_DIR_FOO }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}-foo
          restore-keys: |
            ${{ runner.os }}-buildx-foo

      # Load cached foo docker-formatted tarball into local image
      # repository
      - name: Load cached foo docker image tarball
        run: |
          docker load -i ${{ env.IMAGE_CACHE_DIR_FOO }}/${{ env.IMAGE_TAR_FILE_FOO }}            

      # Use buildx with 'docker' driver so that it is able to access images stored in the
      # local registry (this precludes the possibility of multi-platform images)
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      # List docker images in local repository to confirm exactly what tags were
      # created
      - name: List docker images
        run: docker images          

      - name: Initialize cache for storing docker image
        uses: actions/cache@v3
        with:
          path: ${{ env.IMAGE_CACHE_DIR_BAR }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}-bar
          restore-keys: |
            ${{ runner.os }}-buildx-bar-

      - name: Ensure cache dir exists
        run: if [ ! -d "${{ env.IMAGE_CACHE_DIR_BAR }}" ]; then mkdir ${{ env.IMAGE_CACHE_DIR_BAR }}; fi

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build image
      - name: Build and cache image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: docker/${{ env.DOCKER_DIR_BAR }}
          file: docker/${{ env.DOCKER_DIR_BAR }}/${{ env.DOCKERFILE_NAME }}
          build-args: |
            "IMAGE_FOO=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_FOO }}"
          labels: ${{ steps.meta.outputs.labels }}
          # cache-to: type=local,dest=${{ env.IMAGE_CACHE_DIR_BAR }}

      # List docker images in local repository to confirm exactly what tags were
      # created
      - name: List docker images
        run: docker images        

  build-bar:
    runs-on: ubuntu-latest
    needs: cache-bar

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore bar docker image cache
        uses: actions/cache@v3
        with:
          path: ${{ env.IMAGE_CACHE_DIR_BAR }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}-bar
          restore-keys: |
            ${{ runner.os }}-buildx-bar

      # Login against a Docker registry if releasing
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name == 'release'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build image
      - name: Build and push image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: docker/${{ env.DOCKER_DIR_BAR }}
          file: docker/${{ env.DOCKER_DIR_BAR }}/${{ env.DOCKERFILE_NAME }}
          push: ${{ github.event_name == 'release' }}
          build-args: |
            "IMAGE_FOO=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_FOO }}"
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}          
          cache-from: type=local,dest=${{ env.IMAGE_CACHE_DIR_BAR }}

      # List docker images in local repository to confirm exactly what tags were
      # created
      - name: List docker images
        run: docker images